config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "leagues/:id", to: 'pages#home'
  get "leagues/new", to: 'pages#home'
  # API routing
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :leagues, only: [ :index, :show, :create ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :leagues do
    resources :teams
  end
  resources :teams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams, dependent: :destroy
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :league
end

app/controllers/api/v1/leagues_controller.rb
class Api::V1::LeaguesController < ActionController::Base
  def index
    @leagues = League.order(created_at: :desc)
    render json: @leagues
  end

  def show
    @league = League.find(params[:id])
    render json: @league
  end

  def create
    @league = League.create(league_params)
    render json: @league
  end

  private

  def league_params
    params.require(:league).permit(:name, :country, :city, :lat, :long, :logo, :region)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
    @markers = @leagues.map do |league|
      {
        lat: league.lat,
        lng: league.long,
        infoWindow: render_to_string(partial: "infowindow", locals: { league: league })
      }
    end
  end

  def show
    @league = League.find(params[:id])
    @teams = Team.where(league_id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @leagues = League.where(region: "Australia")
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end



  private

  def set_team
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>World Wide Derby</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/leagues/_infowindow.html.erb
<div class="mapboxgl-popup">
  <div class="mapboxgl-popup-content">
    <p><%= link_to league.name, league_path(league.id) %></p>
    <p><%= league.city %>, <%= league.country %></p>
    <%= cl_image_tag league.logo %>
  </div>
</div>

app/views/leagues/index.html.erb
<div class="container">
  <h1>Leagues of roller derby</h1>
  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
  <% @leagues.each do |league| %>
    <%= cl_image_tag league.logo %>

    <h2><%= link_to league.name, league_path(league.id) %></h2>
    <p><%= league.city %>, <%= league.country %></p>
  <% end %>
</div>

app/views/leagues/show.html.erb
<div class="container">
  <%= image_tag @league.logo %>
  <h1><%= @league.name %></h1>
  <p><%= @league.city %>, <%= @league.country %></p>
  <h2>Teams : </h2>
  <% @league.teams.each do |team| %>
    <p><%= team.name %> - Ranking (last update <%= team.ranking_date.strftime('%a %d %b %Y') %>): <%= team.ranking %></p>
  <% end %>
</div>

app/views/pages/home.html.erb
<div id="root" data-leagues="<%= @leagues.to_json %>"></div>
<%= javascript_pack_tag 'rep' %>